name: SITE DO ARTUR
favicon: null
layout_spectrum: 0.24697
typography_spectrum: 0.48787
title: in to thegrid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.8779308907687664
  saturation: 0.375
  rhythmicContrast: 0.6733059491962194
purpose: []
