name: agência de um homem só
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48787
title: in to thegrid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#483619'
    - '#b0804a'
    - '#040601'
    - '#ffd491'
    - '#f8ad55'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
