name: SITE DO ARTUR
favicon: null
layout_spectrum: 0.3602438955567777
typography_spectrum: 0.029645210597664118
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3743156776763499
  lightness: 0.8779308907687664
  saturation: 0.17523751710541546
  rhythmicContrast: 0.6733059491962194
purpose: []
